lightstep/lightstep-tracer-go

- Makefile
- lightstep_thrift/constants.go
- lightstep_thrift/reportingservice.go
- lightstep_thrift/ttypes.go
also, trivial changes to thrift generated files
> add makefile to generate thrift files

- lightstep_thrift/reportingservice.go
- lightstep_thrift/ttypes.go
Updates the generated Thrift code to match the client library metrics updates.  
Note: this only updates the generated code and does not yet update the client library itself to use the metrics.
> Update LightStep Thrift generated code

- lightstep_thrift/reportingservice.go
- lightstep_thrift/ttypes.go
@bcronin per the conversation we had IRL
> Add gauge field to crouton.Metrics thrift struct

- collect.go
- examples/trivial.go
> Adapt to the recent SpanContext changes

- recorder.go
- spans_buffer.go
- thrift_rpc/recorder.go
Reverts lightstep/lightstep-tracer-go#35
> Revert "Double buffer ls-tracer-golang spans"

- recorder.go
- recorder_test.go
Reconnect the client every 5-6 minutes
Allow use of insecure gRPC via Plaintext option
Add Recorder.Close method
> Reconnect clients every 5-6 minutes

- examples/trivial.go
- logencoder.go
- recorder.go
- recorder_test.go
- report_buffer.go
- thrift_rpc/logencoder.go
- thrift_rpc/recorder.go
cc @jmacd and @aliceadelef regarding the treatment of the reportBuffer, especially (which led to some refactoring). I decided to go for an encoding error count rather than internal log records and also changed the way parameters are passed around.
I cleaned up a few misc TODOs along the way, too.
> Move to OpenTracing KeyValue logging

- recorder.go
We can build much better links to traces if we have this.
> expose TracerID

- Makefile
Just not sure how to automate this test in CI.
> Add test for no glog dependency

- Makefile
- lightstep_thrift/reportingservice.go
- lightstep_thrift/ttypes.go
Per plan to support OT KV logging in a more formal way.
> Support KV logging in the thrift protocol

- tracer.go
Interns were tripping over the nil-pointer channel stuff around report loop closing. Using a `sync.Once` allows these channels to work with a little less ceremony.
> Simpler channel management for report loop.

- collector_client_http.go
- lightstep_thrift/constants.go
- lightstep_thrift/reportingservice.go
- lightstep_thrift/ttypes.go
- thrift_0_9_2/lib/go/thrift/simple_server.go
- tracer_transport_thrift_test.go
R: @frenchfrywpepper @ltyson 
Ran `goimports` on the repo.
> run goimports

- CHANGELOG.md
CC: @jmacd @bg451 @joeblubaugh 
FYI: I updated the changelog with the release notes added into github.
> copy release notes from github to changelog

- cmd/sendspan/main.go
> print events when in cmd/sendspan

- CHANGELOG.md
- span.go
- tracer_test.go
> Allow new spans to have external references

- Gopkg.toml
> remove unused dep constraint

- Gopkg.lock
- Gopkg.toml
- Makefile
- bench_test.go
- collector_client.go
- collector_client_grpc.go
- collector_client_http.go
- propagation_binary.go
- proto_converter.go
- proto_logencoder.go
- test_utils_test.go
- tracer_0_14._test.go
- tracer_impl_test.go
- tracer_test.go
- tracer_transport_grpc_test.go
- tracer_transport_proto_test.go
- tracer_transport_test.go
Use gogo 1.2.1 based on lightstep-tracer-common 1.0.3
> Update to gogo 1.2.1

- README.md
- examples/opencensus/main.go
- lightstepoc/README.md
- lightstepoc/exporter.go
- lightstepoc/internal/conversions/package.go
- lightstepoc/options.go
- lightstepoc/package.go
Some open questions:
* Are all of the OC -> OT conversions appropriate? e.g., is this how we should handle `SpanData.Event`?
* What, if anything, should we do with the `MessageEvent`s? Similarly, how should we handle non-child `Link`s?
* What additional configuration, if any, do we want to expose?
* Should this be in a separate repo or this one?
TODO:
* Tests (!)
* README
* Documentation
> Add experimental OpenCensus exporter

- options.go
> fixed minor typo

- lightstepoc/options.go
Adds the ability to set default tags when creating the exporter.
> Add the option to add default tags.

- CHANGELOG.md
- propagation_stack_test.go
- propagation_text.go
> Fix empty sampled flag
