lightstep/lightstep-tracer-go

recorder.go
This is more compact and consistent with other platforms.
(This change got lost in the shuffle of github org renames and such yesterday)
=> Use base 16 for int64 tracer state ids

thrift_0_9_2/lib/go/thrift/http_client.go
=> don’t reuse headers across HTTP calls

recorder.go
Adds @sambati's dropped spans fix to the library.  
(On minor difference from the original diff is this also *no longer* reports the `Counters` field as well, as that data is superseded by the `InternalMetrics` data.)
=> Add spans.dropped metric

recorder.go
It just sets the corresponding basictracer option.
=> Add a lightstep tracer option to drop all span logs.

Makefile, recorder.go
@bensigelman : this is a simple change to normalize the internal LightStep tracer tags to use the `lightstep.*` prefix.  The normalized names allows the LightStep UI to expose what client library was generating the spans in question.
I wasn't able to test this due possibly to a bit of naïveté on my part perhaps, but in any case HEAD in lightstep-tracer does not build against HEAD of opentracing-go / basictracer-go at the moment and, due to the lack of locked versioning in Go, I don't know what commit it is supposed to be building against (thus I could not build it).
May I pass this PR off to you to be merged into and tested along with the next update to the client library?
=> Normalize automatic, internal tracer tags to use the lightstep.* prefix

recorder.go, spans_buffer.go, thrift_rpc/recorder.go
Also:
- Encode Report (incl. serializing JSON payloads) outside the Recorder lock
- Consolidate handling of default options
- Return NoopTracer instead of Tracer with a nil Recorder (inside a non-nil interface, avoid panics)
- Move oldest/youngest/dropped state into the buffer (simplifies things)
- Document immutable vs mutable fields
- Implement ReportTimeout option
=> Double buffer ls-tracer-golang spans

recorder.go, thrift_rpc/recorder.go
Basictracer now supports a `MaxLogPerSpan` options; plumbing this option in
Lightstep as well.
Fixes #46.
=> Add MaxLogsPerSpan option

recorder.go
Ohai!  I noticed this `context.CancelFunc` wasn't being called. Since the lifetime of the context is the RPC call happening right after it, I think a simple defer works fine.
> Calling the CancelFunc cancels the child and its children, removes the parent's reference to the child, and stops any associated timers. Failing to call the CancelFunc leaks the child and its children until the parent is canceled or the timer fires. 
> - https://golang.org/pkg/context
> Canceling this context releases resources associated with it, so code should call cancel as soon as the operations running in this Context complete: [...]
> - https://golang.org/pkg/context/#WithTimeout
=> cancel funcs should always be called on cancellable contexts

recorder.go
Both `NewTracer` and `NewRecorder` accept an `Options` as argument, but only the `NewTracer` call will set proper defaults to the options. To make both entry points behave similarly, I think it makes sense to extract the defaults code into a method/function that then get used consistently in both `NewTracer` and `NewRecorder`.  
e.g: using a bare `Option`: 
```go
NewRecorder(Option{AccessToken: "..."})
``` 
will currently lead to a misbehaving recorder that has timeouts of 0s.
I don't think this is the most elegant way to go about this, I'm happy to rework it! Just want to bring the idea up.
Note: the diff doesn't show the extracted code, it seems to think I moved the first 3 lines of the `NewTracer` function.
=> apply default options to all exported entry points

recorder.go
Tested cockroachdb with and without `UseGPRC` set.
CC @jmacd
=> use separate default host when UseGPRC is set

version.go
Running gofmt from 1.8.3 produces this diff. 
I noticed this when formatting code in a repository that vendors this package. My guess is that this behavior was changed from 1.7 to 1.8, and that the repository was previously formatted with `cmd/gofmt` from 1.7.
=> Run gofmt with Go 1.8

grpc_collector_client.go, interfaces.go, tracer.go, tracer_test.go
FlushLightstepTracer should retry flushing if there is a previous report in flight instead of just bailing.
=> Reliable Flushing

grpc_collector_client.go, options.go
Set the default GRPC MaxCallSendMsgSize to effectively unlimited
(MaxInt32), with an option to override.  This will make
collector-side limits the effective limit, by default.
This limit is new as of grpc-go 1.4.0, so setting it requires grpc-go >= 1.4.0.
There are also some minor style fixes.
=> [Requires grpc-go >= 1.4.0] Set the GRPC MaxCallSendMsgSize.

proto_converter.go
For unknown objects, we support `fmt.Stringer`. We should probably support `error` as well. Not sure if there any other common serializable interfaces we should check for.
- Typecast unknown objects to error and encode the error string.
- do not emit `Unsupported Value` event.
=> Support error values in proto

events.go, tracer.go, tracer_test.go
Missed this one.
- emit a EventTracerDisabled rather than printing to screen.
- but don't emit the event inside of the lock.
=> Add EventTracerDisabled

propagation_binary.go, tracer.go, tracer_transport_test.go
This supports io.Writer for tracer.Inject() and io.Reader for
tracer.Extract() as required by github.com/opentracing/opentracing-go.
Also: fixes to accept opentracing.Binary as parameter for Inject/Extract
instead of lightstep.BinaryCarrier
fixes #147
=> support io.Writer/io.Reader for Inject/Extract

span.go, tracer_test.go
R: @bg451 @jmacd @tedsuo 
This allows the user to set `defer span.Finish()` and call finish early later in the function.
=> make finish calls idempotent

collector_client_grpc.go
R: @frenchfrywpepper @ltyson 
I noticed that we randomize the reconnect period in two places (options.go and the grpc transport). I am removing one of those randomizations because it could make it randomize to a >20% different value.
=> remove redundant reconnect period randomization

collector_client_grpc.go, options.go
R: @frenchfrywpepper @ltyson 
Allows a use to provide additional dial options that will be passed to GRPC on dial. If none are specified the same default behavior will occur.
This helps allows the user to bind custom middleware or have a custom balancer.
=> allow overiding grpc dial options

tracer_0_14._test.go
These prevented the tests from compiling in go 1.11, which is
stricter than previous versions.
=> Remove unused variables

lightstep/rand/rand_suite_test.go
This fixes issues running `ginkgo test`, where ginkgo was unable to
handle the package correctly.
=> Add ginkgo suite file to rand package

.circleci/config.yml
Running `dep ensure` in CI gives us false positives when there are package changes that haven't been committed correctly.
=> Stop running `dep ensure` in CI

CHANGELOG.md, collector_client.go, tracer_test.go
R: @ltyson @aliceadelef 
CC: @lightstep/team-observability @lightstep/team-application-developer 
Default transport to HTTP if none is specified (instead of GRPC). If this tracer is reporting to somewhere using the latest Satellite version, this change will require no update because on the latest Satellite version, all ports accept both GRPC and HTTP traffic.
If the tracer is reporting to an older Satellite, updating the tracer might also require updating the target the report to a different port.
=> default transport to http if none is specified

proto_logencoder.go, proto_logencoder_test.go
R: @iredelmeier
The use of string to encode unsigned integers is considered a temporary fix, while we sort out the OC merger.
=> Encode unsigned integers as strings (temporarily) to avoid signed conversion LS-1175

collector_client.go, collector_client_grpc.go, collector_client_http.go, options.go
@iredelmeier @frenchfrywpepper @JulianGriggs 
This adds the Access Token as a header and metadata for GRPC and HTTP calls for load balancing.
=> Add Access Token metadata and headers to grpc and http reports

cmd/sendspan/main.go, collector_client.go, collector_client_grpc.go, collector_client_http.go, options.go
The objective is to be able to support TLS communication with a Satellite signed by a non-system default Root CA.
=> Add ability to configure custom certs with grpc and http clients

proto_logencoder.go, proto_logencoder_test.go
R: @bg451 @iredelmeier
CC: @jmacd 
I wanted to extend the functionality of the lazy logger to allow emitting 0 fields (for optional fields) or more than one field (for multiple lazy fields computed from the same object).
The one downside I see is that this makes it so the number of fields encoded is not equal to the number of fields passed in. This means that the array can't be pre-allocated to the exact right capacity. I think that's a reasonable trade-off though.
For the expected use case (emitting exactly one field form a lazy logger), this should work mostly as expected. For unexpected use cases, this might be a change in behavior. Before, it was last write wins, but now it will emit all fields.
=> allow lazy loggers to emit 0 -> N log entries instead of just 1

collector_client.go, collector_client_custom.go, collector_client_grpc.go, collector_client_http.go, collector_client_reporter.go, options.go, tracer.go, tracer_impl_test.go
This adds the ability to inject a custom protobuf transport.
This requires migrating protobuf conversion from `collectorClient`s to the `tracerImpl`, which is a hard step away from non-Protobuf transports.
I'm running tracers in a network without access to the collector, so I'd like to bring my own transport API. The `grpcCollectorClient` is close, but crufty.
=> inject collectorpb.CollectorServiceClient

.circleci/config.yml, tracer_impl_test.go
This should fix (with a fairly gross hack...) the data race that's currently preventing other fixes.
In this case, the problem is with a data race that is only possible in tests, and then only with tests that are run from the same internal package (i.e., `package lightstep`). The tests currently write to the tracer's internal state after the tracer has been constructed, which is being accessed concurrently by the run loop that starts during construction.
A "better" fix might be to refactor, e.g., to use an `internal` package. While this may be an architecturally preferable route, it doesn't make sense to invest in a large change with OpenTelemetry on the horizon.
=> Fix test data races

options.go, propagation.go, propagation_b3.go, propagation_lightstep.go, propagation_text.go, tracer.go, tracer_transport_test.go
This change provides the ability to configure B3 headers propagation via a Propagator option parameter when creating a new Tracer:
```go
lightstepTracer := lightstep.NewTracer(lightstep.Options{
AccessToken: "YourAccessToken",
Propagator: "b3",
})
```
The default configuration uses LightStep headers as before. As part of this change, adding a [Propagator interface](https://github.com/lightstep/lightstep-tracer-go/blob/codeboten/b3-headers/propagation.go) to support future formats, currently implemented by [lightstepPropagator](https://github.com/lightstep/lightstep-tracer-go/blob/codeboten/b3-headers/propagation_lightstep.go) and [b3Propagator](https://github.com/lightstep/lightstep-tracer-go/blob/codeboten/b3-headers/propagation_b3.go).
=> Adding B3 header support

.circleci/config.yml
Some tests are running bumping up against the 10 minute default timeout. Bumping this up to unblock us for now.
=> Bumping go test timeout to 20 minutes

lightstepoc/exporter.go, lightstepoc/internal/conversions/conversions_suite_test.go, lightstepoc/internal/conversions/package.go
This fixes a problem with the opencensus ID conversion logic, since `binary.Uvarint` wasn't capturing the value as expected.
=> Change OC -> LS ID conversion logic

tracer.go
Fixes https://github.com/lightstep/lightstep-tracer-go/issues/226
I also made error handling consistent for `NewTracer` - now it emits event only. 
Overall I would suggest totally removing the emit event logic. It is not the best idea to have a global logger, especially for the library: it might cause issues if someone wants some flexibility (e.g running two tracers with different loggers.). Anyway, not a blocker for us here (: 
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>
=> Added new constructor for tracer that propagates error.

propagation_b3.go, propagation_text.go, raw_span.go, tracer_transport_test.go
Adding `sampled` field to SpanContext as a `string` to handle both `true/false` and `1/0` values that could be passed in.
=> Propagate the x-b3-sampled flag correctly

propagation_b3.go, propagation_lightstep.go, propagation_text.go, raw_span.go, tracer_transport_test.go
Moved padding from left to right. Also ensuring the TraceID is not modified as it gets propagated if it started out as 128-bit
=> Pad least significant bits of trace ID

propagation_b3.go, propagation_text.go, raw_span.go, tracer_transport_test.go
This change removes the padding for 64-bit trace IDs as it is no longer needed. In the event of a 128-bit ID that needs to be truncated to 64-bit, the most significant bits will be truncated.
Signed-off-by: Alex Boten <aboten@lightstep.com>
=> Don't pad since b3 supports 64-bit as well as 128-bit trace IDs

options.go, propagation_b3.go, propagation_binary.go, propagation_lightstep.go, propagation_stack.go, propagation_stack_test.go, tracer.go, tracer_transport_test.go
This enables users to configure custom propagators.
Signed-off-by: Alex Boten <aboten@lightstep.com>
=> Use map instead of string to configure propagators

events.go, tracer.go, tracer_test.go
The flush duration is the amount of time it took for the tracer to pack up the records, send them over the network, and rotate buffers. Seeing this measurement is helpful for tuning the min reporting period for the tracer.
Because the reporter loop is serial, this is the minimum time between flushes that the tracer could do. Add a test that this value is measured.
=> Add flush duration to status report struct

README.md
The `OnEvent` function is deprecated, use `SetGlobalEventHandler` instead.
Follow up to PR #158
Related issue #157
=> update README.md to replace mention of OnEvent

lightstepoc/options.go
Adds the ability to override the `DefaultMaxSpan` and set it explicitly.
=> Add option to set `MaxBufferedSpans`

events.go, options.go, tracer_impl_test.go, tracer_test.go
R: @codeboten @kayousterhout 
Upon a call to `NewTracer`, emit a warning event if the service name is unset, describing that a default service name is being used.
=> LS-17453: Emit a warning if the service name is unset upon tracer initialization 

test_utils_test.go
See https://github.com/golang/go/issues/32479
Fix #257.
Signed-off-by: Robert-André Mauchin <zebob.m@gmail.com>
=> Convert id to string using strconv.Itoa

CHANGELOG.md, tracer.go
Adding the ability to disable metrics via the `LS_METRICS_ENABLED` environment variable. Setting this variable to `LS_METRICS_ENABLED=false` will disable system metrics.
Fixes https://github.com/lightstep/lightstep-tracer-go/issues/256
=> feature: Support environment variable to disable metrics

lightstepoc/internal/conversions/conversions_suite_test.go, lightstepoc/internal/conversions/package.go
Port of https://github.com/lightstep/opentelemetry-exporter-go/commit/60b61487ed3e7c0ea66a5589ea0ed35795a75df3 commit
> There are tracing systems which are not capable of propagating the entire 16 bytes of a trace-id. For better interoperability between a fully compliant systems with these existing systems, the following practices are recommended:
When a system creates an outbound message and needs to generate a fully compliant 16 bytes trace-id from a shorter identifier, it SHOULD left pad the original identifier with zeroes. For example, the identifier 53ce929d0e0e4736, SHOULD be converted to trace-id value 000000000000000053ce929d0e0e4736.
When a system receives an inbound message and needs to convert the 16 bytes trace-id to a shorter identifier, the rightmost part of trace-id SHOULD …
=> fix zipkin trace id

.gitignore, options.go, propagation_binary.go, propagation_lightstep.go, propagation_stack_test.go, span.go, tracer.go, tracer_test.go
=> Propagate sampled flag

CHANGELOG.md, events.go, report_buffer.go, tracer.go, tracer_test.go
R: @kayousterhout @codeboten 
CC: @neena @akehlenbeck 
I discovered a bug in reporting dropped and errored spans. Specifically, if span reports are being rejected on the wire, we merge those reports (including the dropped & errored spans) back into the next report. This makes sense because we assume that the server hasn't successfully processed the report and we try again with the totality of the report.
Unfortunately, we also emit a status event with each report attempt (successful or unsuccessful). On unsuccessful reporting attempts, we are emitting a status event with dropped spans and then merging that counter back into the next report attempt. This means that when the next report attempt completes (whether successfully or unsuccessfully) that counter will be reported again (double …
=> Only emit spans dropped within a status interval in the status event report

lightstep/rand/locked_rand.go, lightstep/rand/num_gen.go, util.go
R: @codeboten 
CC: @lightstep/team-ingest 
We discovered that the tracer is generating int64 trace IDs and converting them to uint64s, which means we're only using half of the trace ID space! This PR makes it so we actually generates random uint64 trace IDs. (This should halve our probability of trace ID collisions).
=> LS-21346: lightstep-tracer-go: generate uint64 trace IDs, not int64

CHANGELOG.md, go.mod, go.sum, internal/metrics/metrics.go
Hi, I've updated gopsutil to v3 so macOS/arm64 devices can build this project locally. 
See https://github.com/shirou/gopsutil/issues/1000 regarding gopsutil-v2 incompatibility with macOS/arm64. 
There are similar updates done on other open source repos, eg. https://github.com/kubernetes/minikube/pull/10115
Tested locally with `go version go1.16 darwin/arm64`.
=> Update gopsutil to v3 for macOS/arm64 (Apple M1) compatibility 

propagation_binary.go, tracer_transport_test.go
_Sorry for prematurely opening prior PR (#278), meant to test this in a private forked repo before opening the PR._
The binary carrier was not propagating sampling decisions, PR fixes this so the sampling decision is correctly propagated. The sampling decision wasn't being used after decoding from the wire format; PR simply uses the wire format's sampling decision when decoding.
=> Propagate sampling decisions for binary carrier
